import "./ShareModal.css";
import { useState } from "react";
import { jsPDF } from "jspdf";

export default function ShareModal({

    open,

    onClose,

    result

}) 
{

    const [copied, setCopied] = useState(false);

    console.log("ShareModal open =", open);

if (!open) return null;

    const summary = result?.result?.summary?.en || "";

    const headline = result?.result?.headline || "";

    const risk = result?.result?.risk_level || "";

    const score = result?.result?.risk_score || 0;

    const report = `

SurakshaSathi AI Report

Risk Level : ${risk}

Risk Score : ${score}

Scam Type : ${headline}

Summary :

${summary}

Generated by SurakshaSathi AI

`;

    const handleShare = async () => {

        if (navigator.share) {

            try {

                await navigator.share({

                    title: "SurakshaSathi AI Report",

                    text: report

                });

            }

            catch(err){

                console.log(err);

            }

        }

        else{

            handleCopy();

        }

    };

    const handleCopy = async ()=>{

        await navigator.clipboard.writeText(report);

        setCopied(true);

        setTimeout(()=>{

            setCopied(false);

        },2000);

    };

    const handleWhatsApp=()=>{

        const url=`https://wa.me/?text=${encodeURIComponent(report)}`;

        window.open(url,"_blank");

    };

    const handleEmail=()=>{

        const subject="SurakshaSathi AI Scam Report";

        const body=encodeURIComponent(report);

        window.location.href=`mailto:?subject=${subject}&body=${body}`;

    };

    const downloadTXT=()=>{

        const blob=new Blob(

            [report],

            {

                type:"text/plain"

            }

        );

        const url=URL.createObjectURL(blob);

        const a=document.createElement("a");

        const date=new Date();

        a.href=url;

        a.download=`SurakshaSathi_Report_${date.getTime()}.txt`;

        a.click();

        URL.revokeObjectURL(url);

    };

    const exportPDF = () => {

    const doc = new jsPDF();

    const risk = result?.result?.risk_level || "Unknown";

    const score = result?.result?.risk_score || 0;

    const headline = result?.result?.headline || "Unknown";

    const summary = result?.result?.summary?.en || "";

    const warnings = result?.red_flags || [];

    const actions = result?.actions || [];

    const date = new Date().toLocaleString();

    let y = 20;

    // Title
    doc.setFontSize(22);
    doc.setTextColor(0, 102, 204);
    doc.text("SurakshaSathi AI Report", 20, y);

    y += 15;

    // Basic Information
    doc.setFontSize(12);
    doc.setTextColor(0);

    doc.text(`Generated : ${date}`, 20, y);
    y += 10;

    doc.text(`Risk Level : ${risk}`, 20, y);
    y += 8;

    doc.text(`Risk Score : ${score}%`, 20, y);
    y += 8;

    doc.text(`Scam Type : ${headline}`, 20, y);

    y += 15;

    // Summary
    doc.setFontSize(15);
    doc.text("Summary", 20, y);

    y += 10;

    doc.setFontSize(12);

    const wrappedSummary = doc.splitTextToSize(summary, 170);

    doc.text(wrappedSummary, 20, y);

    y += wrappedSummary.length * 7 + 10;

    // Warning Signs
    doc.setFontSize(15);
    doc.text("Warning Signs", 20, y);

    y += 10;

    doc.setFontSize(12);

    warnings.forEach((item) => {

        doc.text(`• ${item.en}`, 25, y);

        y += 8;

    });

    y += 5;

    // Action Steps
    doc.setFontSize(15);
    doc.text("Recommended Actions", 20, y);

    y += 10;

    doc.setFontSize(12);

    actions.forEach((item) => {

        doc.text(`• ${item.en}`, 25, y);

        y += 8;

    });

    y += 10;

    doc.setFontSize(11);

    doc.setTextColor(120);

    doc.text(
        "Generated by SurakshaSathi AI",
        20,
        y
    );

    doc.save(
        `SurakshaSathi_Report_${Date.now()}.pdf`
    );

};

    const analyzeAgain=()=>{

        window.location.reload();

    };

    return(

        <div

            className="share-overlay"

            onClick={onClose}

        >

            <div

                className="share-modal"

                onClick={(e)=>e.stopPropagation()}

            >

                <div className="share-header">

                    <h2>

                        📤 Share & Export

                    </h2>

                    <button

                        className="close-modal"

                        onClick={onClose}

                    >

                        ✕

                    </button>

                </div>

                <div className="share-options">

                    <button

                        className="share-option"

                        onClick={handleShare}

                    >

                        <span>

                            📤

                        </span>

                        <div>

                            <h3>

                                Share Analysis

                            </h3>

                            <p>

                                Native Share API

                            </p>

                        </div>

                    </button>

                    <button

                        className="share-option"

                        onClick={handleWhatsApp}

                    >

                        <span>

                            💬

                        </span>

                        <div>

                            <h3>

                                WhatsApp

                            </h3>

                            <p>

                                Share via WhatsApp

                            </p>

                        </div>

                    </button>

                    <button

                        className="share-option"

                        onClick={handleEmail}

                    >

                        <span>

                            📧

                        </span>

                        <div>

                            <h3>

                                Email

                            </h3>

                            <p>

                                Send report

                            </p>

                        </div>

                    </button>
                                        <button

                        className="share-option"

                        onClick={handleCopy}

                    >

                        <span>

                            📋

                        </span>

                        <div>

                            <h3>

                                {copied ? "Copied!" : "Copy Summary"}

                            </h3>

                            <p>

                                Copy to Clipboard

                            </p>

                        </div>

                    </button>

                    <button

                        className="share-option"

                        onClick={exportPDF}

                    >

                        <span>

                            📄

                        </span>

                        <div>

                            <h3>

                                Export PDF

                            </h3>

                            <p>

                                Download PDF Report

                            </p>

                        </div>

                    </button>

                    <button

                        className="share-option"

                        onClick={downloadTXT}

                    >

                        <span>

                            📥

                        </span>

                        <div>

                            <h3>

                                Download TXT

                            </h3>

                            <p>

                                Save Text Report

                            </p>

                        </div>

                    </button>

                    <button

                        className="share-option"

                        onClick={analyzeAgain}

                    >

                        <span>

                            🔄

                        </span>

                        <div>

                            <h3>

                                Analyze Again

                            </h3>

                            <p>

                                Start a New Scan

                            </p>

                        </div>

                    </button>

                </div>

            </div>

        </div>

    );

}